<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Analytics Report</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 12px; }
        h1 { font-size: 18px; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f2f2f2; font-weight: bold; }
        .footer { margin-top: 20px; font-size: 10px; color: #666; }
    </style>
</head>
<body>
    <h1>Analytics Report</h1>
    <p>Generated at: {{ $generatedAt }}</p>

    <h2>Products</h2>
    <table>
        <tr><th>Database</th><th>Count</th></tr>
        <tr><td>Primary</td><td>{{ $primaryProducts }}</td></tr>
        <tr><td>Secondary</td><td>{{ $secondaryProducts }}</td></tr>
        <tr><th>Total</th><th>{{ $totalProducts }}</th></tr>
    </table>

    <h2>Blogs</h2>
    <table>
        <tr><th>Total</th><th>Published</th></tr>
        <tr><td>{{ $totalBlogs }}</td><td>{{ $publishedBlogs }}</td></tr>
    </table>

    <h2>Categories & Tags</h2>
    <table>
        <tr><th>Categories</th><th>Tags</th></tr>
        <tr><td>{{ $categories }}</td><td>{{ $tags }}</td></tr>
    </table>

    <div class="footer">
        <p>Report generated by Laravel Multi-Database Manager</p>
    </div>
</body>
</html>
